deployment:
  name: cure-freedom-bot
  image: __IMAGE_NAME__:__TAG__
  imagePullPolicy: Always
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: cure-freedom-bot
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

configmap:
  name: cure-freedom-bot-config

secret:
  name: telegram-token
  telegramToken: __TELEGRAM_TOKEN__
