apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      {{- range $k, $v := .Values.deployment.labels }}
      {{ $k }}: {{ $v }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $k, $v := .Values.deployment.labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    spec:
      containers:
      - name: app
        image: {{ .Values.deployment.image }}:{{ .Values.appVersion }}
        envFrom:
          - secretRef:
              name: telegram-token
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 256Mi
